package com.google.android.gms.internal.ads;

import S5.k1;
import S5.l2;
import S5.q2;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* loaded from: /storage/emulated/0/Android/data/com.apktools.app.decompile/files/decompile_temp/jadx/classes3.dex */
public final class zzbyz extends y6.a {
    public static final Parcelable.Creator CREATOR = new zzbza();
    public final long zzA;
    public final String zzB;
    public final float zzC;
    public final int zzD;
    public final int zzE;
    public final boolean zzF;
    public final String zzG;
    public final boolean zzH;
    public final String zzI;
    public final boolean zzJ;
    public final int zzK;
    public final Bundle zzL;
    public final String zzM;
    public final k1 zzN;
    public final boolean zzO;
    public final Bundle zzP;
    public final String zzQ;
    public final String zzR;
    public final String zzS;
    public final boolean zzT;
    public final List zzU;
    public final String zzV;
    public final List zzW;
    public final int zzX;
    public final boolean zzY;
    public final boolean zzZ;
    public final int zza;
    public final boolean zzaa;
    public final ArrayList zzab;
    public final String zzac;
    public final zzbqs zzad;
    public final String zzae;
    public final Bundle zzaf;
    public final Bundle zzb;
    public final l2 zzc;
    public final q2 zzd;
    public final String zze;
    public final ApplicationInfo zzf;
    public final PackageInfo zzg;
    public final String zzh;
    public final String zzi;
    public final String zzj;
    public final W5.a zzk;
    public final Bundle zzl;
    public final int zzm;
    public final List zzn;
    public final Bundle zzo;
    public final boolean zzp;
    public final int zzq;
    public final int zzr;
    public final float zzs;
    public final String zzt;
    public final long zzu;
    public final String zzv;
    public final List zzw;
    public final String zzx;
    public final zzbkh zzy;
    public final List zzz;

    public zzbyz(int i, Bundle bundle, l2 l2Var, q2 q2Var, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, W5.a aVar, Bundle bundle2, int i2, List list, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, List list2, String str7, zzbkh zzbkhVar, List list3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, k1 k1Var, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, List list4, String str15, List list5, int i8, boolean z7, boolean z8, boolean z9, ArrayList arrayList, String str16, zzbqs zzbqsVar, String str17, Bundle bundle6) {
        this.zza = i;
        this.zzb = bundle;
        this.zzc = l2Var;
        this.zzd = q2Var;
        this.zze = str;
        this.zzf = applicationInfo;
        this.zzg = packageInfo;
        this.zzh = str2;
        this.zzi = str3;
        this.zzj = str4;
        this.zzk = aVar;
        this.zzl = bundle2;
        this.zzm = i2;
        this.zzn = list;
        this.zzz = list3 == null ? Collections.emptyList() : Collections.unmodifiableList(list3);
        this.zzo = bundle3;
        this.zzp = z;
        this.zzq = i3;
        this.zzr = i4;
        this.zzs = f;
        this.zzt = str5;
        this.zzu = j;
        this.zzv = str6;
        this.zzw = list2 == null ? Collections.emptyList() : Collections.unmodifiableList(list2);
        this.zzx = str7;
        this.zzy = zzbkhVar;
        this.zzA = j2;
        this.zzB = str8;
        this.zzC = f2;
        this.zzH = z2;
        this.zzD = i5;
        this.zzE = i6;
        this.zzF = z3;
        this.zzG = str9;
        this.zzI = str10;
        this.zzJ = z4;
        this.zzK = i7;
        this.zzL = bundle4;
        this.zzM = str11;
        this.zzN = k1Var;
        this.zzO = z5;
        this.zzP = bundle5;
        this.zzQ = str12;
        this.zzR = str13;
        this.zzS = str14;
        this.zzT = z6;
        this.zzU = list4;
        this.zzV = str15;
        this.zzW = list5;
        this.zzX = i8;
        this.zzY = z7;
        this.zzZ = z8;
        this.zzaa = z9;
        this.zzab = arrayList;
        this.zzac = str16;
        this.zzad = zzbqsVar;
        this.zzae = str17;
        this.zzaf = bundle6;
    }

    public final void writeToParcel(Parcel parcel, int i) {
        int i2 = this.zza;
        int a = y6.c.a(parcel);
        y6.c.t(parcel, 1, i2);
        y6.c.j(parcel, 2, this.zzb, false);
        y6.c.C(parcel, 3, this.zzc, i, false);
        y6.c.C(parcel, 4, this.zzd, i, false);
        y6.c.E(parcel, 5, this.zze, false);
        y6.c.C(parcel, 6, this.zzf, i, false);
        y6.c.C(parcel, 7, this.zzg, i, false);
        y6.c.E(parcel, 8, this.zzh, false);
        y6.c.E(parcel, 9, this.zzi, false);
        y6.c.E(parcel, 10, this.zzj, false);
        y6.c.C(parcel, 11, this.zzk, i, false);
        y6.c.j(parcel, 12, this.zzl, false);
        y6.c.t(parcel, 13, this.zzm);
        y6.c.G(parcel, 14, this.zzn, false);
        y6.c.j(parcel, 15, this.zzo, false);
        y6.c.g(parcel, 16, this.zzp);
        y6.c.t(parcel, 18, this.zzq);
        y6.c.t(parcel, 19, this.zzr);
        y6.c.p(parcel, 20, this.zzs);
        y6.c.E(parcel, 21, this.zzt, false);
        y6.c.x(parcel, 25, this.zzu);
        y6.c.E(parcel, 26, this.zzv, false);
        y6.c.G(parcel, 27, this.zzw, false);
        y6.c.E(parcel, 28, this.zzx, false);
        y6.c.C(parcel, 29, this.zzy, i, false);
        y6.c.G(parcel, 30, this.zzz, false);
        y6.c.x(parcel, 31, this.zzA);
        y6.c.E(parcel, 33, this.zzB, false);
        y6.c.p(parcel, 34, this.zzC);
        y6.c.t(parcel, 35, this.zzD);
        y6.c.t(parcel, 36, this.zzE);
        y6.c.g(parcel, 37, this.zzF);
        y6.c.E(parcel, 39, this.zzG, false);
        y6.c.g(parcel, 40, this.zzH);
        y6.c.E(parcel, 41, this.zzI, false);
        y6.c.g(parcel, 42, this.zzJ);
        y6.c.t(parcel, 43, this.zzK);
        y6.c.j(parcel, 44, this.zzL, false);
        y6.c.E(parcel, 45, this.zzM, false);
        y6.c.C(parcel, 46, this.zzN, i, false);
        y6.c.g(parcel, 47, this.zzO);
        y6.c.j(parcel, 48, this.zzP, false);
        y6.c.E(parcel, 49, this.zzQ, false);
        y6.c.E(parcel, 50, this.zzR, false);
        y6.c.E(parcel, 51, this.zzS, false);
        y6.c.g(parcel, 52, this.zzT);
        y6.c.v(parcel, 53, this.zzU, false);
        y6.c.E(parcel, 54, this.zzV, false);
        y6.c.G(parcel, 55, this.zzW, false);
        y6.c.t(parcel, 56, this.zzX);
        y6.c.g(parcel, 57, this.zzY);
        y6.c.g(parcel, 58, this.zzZ);
        y6.c.g(parcel, 59, this.zzaa);
        y6.c.G(parcel, 60, this.zzab, false);
        y6.c.E(parcel, 61, this.zzac, false);
        y6.c.C(parcel, 63, this.zzad, i, false);
        y6.c.E(parcel, 64, this.zzae, false);
        y6.c.j(parcel, 65, this.zzaf, false);
        y6.c.b(parcel, a);
    }
}
