package X6;

import W6.y;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.common.internal.r;

/* loaded from: /storage/emulated/0/Android/data/com.apktools.app.decompile/files/decompile_temp/jadx/classes3.dex */
public final class f extends y {
    public static final Parcelable.Creator CREATOR = new g();
    public final boolean a;
    public final boolean b;
    public final boolean c;
    public final boolean d;
    public final boolean e;
    public final boolean f;
    public final boolean g;
    public final boolean h;
    public final boolean i;
    public final boolean j;

    public f(boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10) {
        this.a = z;
        this.b = z2;
        this.c = z3;
        this.d = z4;
        this.e = z5;
        this.f = z6;
        this.g = z7;
        this.h = z8;
        this.i = z9;
        this.j = z10;
    }

    public final boolean equals(Object obj) {
        if (!(obj instanceof f)) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        f fVar = (f) obj;
        return this.a == fVar.a && this.b == fVar.b && this.c == fVar.c && this.d == fVar.d && this.e == fVar.e && this.f == fVar.f && this.g == fVar.g && this.h == fVar.h && this.i == fVar.i && this.j == fVar.j;
    }

    public final int hashCode() {
        return r.c(Boolean.valueOf(this.a), Boolean.valueOf(this.b), Boolean.valueOf(this.c), Boolean.valueOf(this.d), Boolean.valueOf(this.e), Boolean.valueOf(this.f), Boolean.valueOf(this.g), Boolean.valueOf(this.h), Boolean.valueOf(this.i), Boolean.valueOf(this.j));
    }

    public final String toString() {
        return r.d(this).a("forbiddenToHavePlayerProfile", Boolean.valueOf(this.a)).a("requiresParentPermissionToShareData", Boolean.valueOf(this.b)).a("hasSettingsControlledByParent", Boolean.valueOf(this.c)).a("requiresParentPermissionToUsePlayTogether", Boolean.valueOf(this.d)).a("canUseOnlyAutoGeneratedGamerTag", Boolean.valueOf(this.e)).a("forbiddenToRecordVideo", Boolean.valueOf(this.f)).a("shouldSeeEquallyWeightedButtonsInConsents", Boolean.valueOf(this.g)).a("requiresParentConsentToUseAutoSignIn", Boolean.valueOf(this.h)).a("shouldSeeSimplifiedConsentMessages", Boolean.valueOf(this.i)).a("forbiddenToUseProfilelessRecall", Boolean.valueOf(this.j)).toString();
    }

    public final void writeToParcel(Parcel parcel, int i) {
        boolean z = this.a;
        int a = y6.c.a(parcel);
        y6.c.g(parcel, 1, z);
        y6.c.g(parcel, 2, this.b);
        y6.c.g(parcel, 3, this.c);
        y6.c.g(parcel, 4, this.d);
        y6.c.g(parcel, 5, this.e);
        y6.c.g(parcel, 6, this.f);
        y6.c.g(parcel, 7, this.g);
        y6.c.g(parcel, 8, this.h);
        y6.c.g(parcel, 9, this.i);
        y6.c.g(parcel, 10, this.j);
        y6.c.b(parcel, a);
    }
}
