package com.android.billingclient.api;

import com.android.billingclient.api.BillingResult;

/* loaded from: /storage/emulated/0/Android/data/com.apktools.app.decompile/files/decompile_temp/jadx/classes3.dex */
public abstract class k {
    public static final BillingResult A;
    public static final BillingResult B;
    public static final BillingResult C;
    public static final BillingResult D;
    public static final BillingResult E;
    public static final BillingResult F;
    public static final BillingResult a;
    public static final BillingResult b;
    public static final BillingResult c;
    public static final BillingResult d;
    public static final BillingResult e;
    public static final BillingResult f;
    public static final BillingResult g;
    public static final BillingResult h;
    public static final BillingResult i;
    public static final BillingResult j;
    public static final BillingResult k;
    public static final BillingResult l;
    public static final BillingResult m;
    public static final BillingResult n;
    public static final BillingResult o;
    public static final BillingResult p;
    public static final BillingResult q;
    public static final BillingResult r;
    public static final BillingResult s;
    public static final BillingResult t;
    public static final BillingResult u;
    public static final BillingResult v;
    public static final BillingResult w;
    public static final BillingResult x;
    public static final BillingResult y;
    public static final BillingResult z;

    static {
        BillingResult.Builder newBuilder = BillingResult.newBuilder();
        newBuilder.setResponseCode(3);
        newBuilder.setDebugMessage("Google Play In-app Billing API version is less than 3");
        newBuilder.build();
        BillingResult.Builder newBuilder2 = BillingResult.newBuilder();
        newBuilder2.setResponseCode(3);
        newBuilder2.setDebugMessage("Google Play In-app Billing API version is less than 9");
        a = newBuilder2.build();
        BillingResult.Builder newBuilder3 = BillingResult.newBuilder();
        newBuilder3.setResponseCode(3);
        newBuilder3.setDebugMessage("Billing service unavailable on device.");
        b = newBuilder3.build();
        BillingResult.Builder newBuilder4 = BillingResult.newBuilder();
        newBuilder4.setResponseCode(2);
        newBuilder4.setDebugMessage("Billing service unavailable on device.");
        c = newBuilder4.build();
        BillingResult.Builder newBuilder5 = BillingResult.newBuilder();
        newBuilder5.setResponseCode(5);
        newBuilder5.setDebugMessage("Client is already in the process of connecting to billing service.");
        d = newBuilder5.build();
        BillingResult.Builder newBuilder6 = BillingResult.newBuilder();
        newBuilder6.setResponseCode(5);
        newBuilder6.setDebugMessage("The list of SKUs can't be empty.");
        newBuilder6.build();
        BillingResult.Builder newBuilder7 = BillingResult.newBuilder();
        newBuilder7.setResponseCode(5);
        newBuilder7.setDebugMessage("SKU type can't be empty.");
        newBuilder7.build();
        BillingResult.Builder newBuilder8 = BillingResult.newBuilder();
        newBuilder8.setResponseCode(5);
        newBuilder8.setDebugMessage("Product type can't be empty.");
        e = newBuilder8.build();
        BillingResult.Builder newBuilder9 = BillingResult.newBuilder();
        newBuilder9.setResponseCode(-2);
        newBuilder9.setDebugMessage("Client does not support extra params.");
        f = newBuilder9.build();
        BillingResult.Builder newBuilder10 = BillingResult.newBuilder();
        newBuilder10.setResponseCode(5);
        newBuilder10.setDebugMessage("Invalid purchase token.");
        g = newBuilder10.build();
        BillingResult.Builder newBuilder11 = BillingResult.newBuilder();
        newBuilder11.setResponseCode(6);
        newBuilder11.setDebugMessage("An internal error occurred.");
        h = newBuilder11.build();
        BillingResult.Builder newBuilder12 = BillingResult.newBuilder();
        newBuilder12.setResponseCode(5);
        newBuilder12.setDebugMessage("SKU can't be null.");
        newBuilder12.build();
        BillingResult.Builder newBuilder13 = BillingResult.newBuilder();
        newBuilder13.setResponseCode(0);
        i = newBuilder13.build();
        BillingResult.Builder newBuilder14 = BillingResult.newBuilder();
        newBuilder14.setResponseCode(-1);
        newBuilder14.setDebugMessage("Service connection is disconnected.");
        j = newBuilder14.build();
        BillingResult.Builder newBuilder15 = BillingResult.newBuilder();
        newBuilder15.setResponseCode(2);
        newBuilder15.setDebugMessage("Timeout communicating with service.");
        k = newBuilder15.build();
        BillingResult.Builder newBuilder16 = BillingResult.newBuilder();
        newBuilder16.setResponseCode(-2);
        newBuilder16.setDebugMessage("Client does not support subscriptions.");
        l = newBuilder16.build();
        BillingResult.Builder newBuilder17 = BillingResult.newBuilder();
        newBuilder17.setResponseCode(-2);
        newBuilder17.setDebugMessage("Client does not support subscriptions update.");
        m = newBuilder17.build();
        BillingResult.Builder newBuilder18 = BillingResult.newBuilder();
        newBuilder18.setResponseCode(-2);
        newBuilder18.setDebugMessage("Client does not support get purchase history.");
        newBuilder18.build();
        BillingResult.Builder newBuilder19 = BillingResult.newBuilder();
        newBuilder19.setResponseCode(-2);
        newBuilder19.setDebugMessage("Client does not support price change confirmation.");
        n = newBuilder19.build();
        BillingResult.Builder newBuilder20 = BillingResult.newBuilder();
        newBuilder20.setResponseCode(-2);
        newBuilder20.setDebugMessage("Play Store version installed does not support cross selling products.");
        o = newBuilder20.build();
        BillingResult.Builder newBuilder21 = BillingResult.newBuilder();
        newBuilder21.setResponseCode(-2);
        newBuilder21.setDebugMessage("Client does not support multi-item purchases.");
        p = newBuilder21.build();
        BillingResult.Builder newBuilder22 = BillingResult.newBuilder();
        newBuilder22.setResponseCode(-2);
        newBuilder22.setDebugMessage("Client does not support offer_id_token.");
        q = newBuilder22.build();
        BillingResult.Builder newBuilder23 = BillingResult.newBuilder();
        newBuilder23.setResponseCode(-2);
        newBuilder23.setDebugMessage("Client does not support ProductDetails.");
        r = newBuilder23.build();
        BillingResult.Builder newBuilder24 = BillingResult.newBuilder();
        newBuilder24.setResponseCode(-2);
        newBuilder24.setDebugMessage("Client does not support in-app messages.");
        s = newBuilder24.build();
        BillingResult.Builder newBuilder25 = BillingResult.newBuilder();
        newBuilder25.setResponseCode(-2);
        newBuilder25.setDebugMessage("Client does not support user choice billing.");
        newBuilder25.build();
        BillingResult.Builder newBuilder26 = BillingResult.newBuilder();
        newBuilder26.setResponseCode(-2);
        newBuilder26.setDebugMessage("Play Store version installed does not support external offer.");
        t = newBuilder26.build();
        BillingResult.Builder newBuilder27 = BillingResult.newBuilder();
        newBuilder27.setResponseCode(-2);
        newBuilder27.setDebugMessage("Play Store version installed does not support multi-item purchases with season pass in one cart.");
        u = newBuilder27.build();
        BillingResult.Builder newBuilder28 = BillingResult.newBuilder();
        newBuilder28.setResponseCode(-2);
        newBuilder28.setDebugMessage("Play Store version installed does not support querying AutoPay plan purchase.");
        v = newBuilder28.build();
        BillingResult.Builder newBuilder29 = BillingResult.newBuilder();
        newBuilder29.setResponseCode(-2);
        newBuilder29.setDebugMessage("Play Store version installed does not support including suspended subscriptions.");
        w = newBuilder29.build();
        BillingResult.Builder newBuilder30 = BillingResult.newBuilder();
        newBuilder30.setResponseCode(5);
        newBuilder30.setDebugMessage("Unknown feature");
        x = newBuilder30.build();
        BillingResult.Builder newBuilder31 = BillingResult.newBuilder();
        newBuilder31.setResponseCode(-2);
        newBuilder31.setDebugMessage("Play Store version installed does not support get billing config.");
        y = newBuilder31.build();
        BillingResult.Builder newBuilder32 = BillingResult.newBuilder();
        newBuilder32.setResponseCode(-2);
        newBuilder32.setDebugMessage("Query product details with serialized docid is not supported.");
        z = newBuilder32.build();
        BillingResult.Builder newBuilder33 = BillingResult.newBuilder();
        newBuilder33.setResponseCode(-2);
        newBuilder33.setDebugMessage("Play Store version installed does not support launching external offer flow.");
        A = newBuilder33.build();
        BillingResult.Builder newBuilder34 = BillingResult.newBuilder();
        newBuilder34.setResponseCode(4);
        newBuilder34.setDebugMessage("Item is unavailable for purchase.");
        B = newBuilder34.build();
        BillingResult.Builder newBuilder35 = BillingResult.newBuilder();
        newBuilder35.setResponseCode(-2);
        newBuilder35.setDebugMessage("Query product details with developer specified account is not supported.");
        C = newBuilder35.build();
        BillingResult.Builder newBuilder36 = BillingResult.newBuilder();
        newBuilder36.setResponseCode(-2);
        newBuilder36.setDebugMessage("Play Store version installed does not support alternative billing only.");
        D = newBuilder36.build();
        BillingResult.Builder newBuilder37 = BillingResult.newBuilder();
        newBuilder37.setResponseCode(5);
        newBuilder37.setDebugMessage("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        E = newBuilder37.build();
        BillingResult.Builder newBuilder38 = BillingResult.newBuilder();
        newBuilder38.setResponseCode(6);
        newBuilder38.setDebugMessage("An error occurred while retrieving billing override.");
        F = newBuilder38.build();
        BillingResult.Builder newBuilder39 = BillingResult.newBuilder();
        newBuilder39.setResponseCode(-2);
        newBuilder39.setDebugMessage("Play Store version installed does not support the provided billing program.");
        newBuilder39.build();
    }

    public static BillingResult a(int i2, String str) {
        BillingResult.Builder newBuilder = BillingResult.newBuilder();
        newBuilder.setResponseCode(i2);
        newBuilder.setDebugMessage(str);
        return newBuilder.build();
    }
}
