package nb;

import Ca.p;

/* loaded from: /storage/emulated/0/Android/data/com.apktools.app.decompile/files/decompile_temp/jadx/classes5.dex */
public interface a {

    public static final class a {
        public static Object[] a(a aVar, int i) {
            throw new p("Generated by Android Extensions automatically");
        }
    }
}
