package k7;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

/* loaded from: /storage/emulated/0/Android/data/com.apktools.app.decompile/files/decompile_temp/jadx/classes4.dex */
public abstract class f2 {
    public static final e2 A;
    public static final e2 A0;
    public static final e2 B;
    public static final e2 B0;
    public static final e2 C;
    public static final e2 C0;
    public static final e2 D;
    public static final e2 D0;
    public static final e2 E;
    public static final e2 E0;
    public static final e2 F;
    public static final e2 F0;
    public static final e2 G;
    public static final e2 G0;
    public static final e2 H;
    public static final e2 H0;
    public static final e2 I;
    public static final e2 I0;
    public static final e2 J;
    public static final e2 J0;
    public static final e2 K;
    public static final e2 K0;
    public static final e2 L;
    public static final e2 L0;
    public static final e2 M;
    public static final e2 M0;
    public static final e2 N;
    public static final e2 N0;
    public static final e2 O;
    public static final e2 O0;
    public static final e2 P;
    public static final e2 P0;
    public static final e2 Q;
    public static final e2 Q0;
    public static final e2 R;
    public static final e2 R0;
    public static final e2 S;
    public static final e2 S0;
    public static final e2 T;
    public static final e2 T0;
    public static final e2 U;
    public static final e2 U0;
    public static final e2 V;
    public static final e2 V0;
    public static final e2 W;
    public static final e2 W0;
    public static final e2 X;
    public static final e2 X0;
    public static final e2 Y;
    public static final e2 Y0;
    public static final e2 Z;
    public static final e2 Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final e2 a0;
    public static final e2 a1;
    public static final e2 b;
    public static final e2 b0;
    public static final e2 b1;
    public static final e2 c;
    public static final e2 c0;
    public static final e2 c1;
    public static final e2 d;
    public static final e2 d0;
    public static final e2 d1;
    public static final e2 e;
    public static final e2 e0;
    public static final e2 e1;
    public static final e2 f;
    public static final e2 f0;
    public static final e2 f1;
    public static final e2 g;
    public static final e2 g0;
    public static final e2 g1;
    public static final e2 h;
    public static final e2 h0;
    public static final e2 h1;
    public static final e2 i;
    public static final e2 i0;
    public static final e2 i1;
    public static final e2 j;
    public static final e2 j0;
    public static final e2 j1;
    public static final e2 k;
    public static final e2 k0;
    public static final e2 k1;
    public static final e2 l;
    public static final e2 l0;
    public static final e2 l1;
    public static final e2 m;
    public static final e2 m0;
    public static final e2 n;
    public static final e2 n0;
    public static final e2 o;
    public static final e2 o0;
    public static final e2 p;
    public static final e2 p0;
    public static final e2 q;
    public static final e2 q0;
    public static final e2 r;
    public static final e2 r0;
    public static final e2 s;
    public static final e2 s0;
    public static final e2 t;
    public static final e2 t0;
    public static final e2 u;
    public static final e2 u0;
    public static final e2 v;
    public static final e2 v0;
    public static final e2 w;
    public static final e2 w0;
    public static final e2 x;
    public static final e2 x0;
    public static final e2 y;
    public static final e2 y0;
    public static final e2 z;
    public static final e2 z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, 10000L, X1.a, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, 3600000L, Q.a, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, j0.a, false);
        e = a("measurement.config.cache_time", 86400000L, 3600000L, u0.a, false);
        f = a("measurement.config.url_scheme", "https", "https", G0.a, false);
        g = a("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", R0.a, false);
        h = a("measurement.upload.max_bundles", 100, 100, c1.a, false);
        i = a("measurement.upload.max_batch_size", 65536, 65536, o1.a, false);
        j = a("measurement.upload.max_bundle_size", 65536, 65536, z1.a, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, 1000, L1.a, false);
        l = a("measurement.upload.max_events_per_day", 100000, 100000, W1.a, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, 1000, Y.a, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, 50000, Z.a, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, 10000, a0.a, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, 10, b0.a, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, 100000, c0.a, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", e0.a, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", "https://app-measurement.com/s/d", f0.a, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", "", g0.a, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", "404,429,503,504", h0.a, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, 600000L, i0.a, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, 21600000L, k0.a, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, 1800000L, l0.a, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, 21600000L, m0.a, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, 10, n0.a, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, 5000, o0.a, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, 5, p0.a, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, 5000L, q0.a, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, 1000L, r0.a, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, 600000L, s0.a, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, 14400000L, t0.a, false);
        G = a("measurement.upload.backoff_period", 43200000L, 43200000L, v0.a, false);
        H = a("measurement.upload.window_interval", 3600000L, 3600000L, w0.a, false);
        I = a("measurement.upload.interval", 3600000L, 3600000L, x0.a, false);
        J = a("measurement.upload.realtime_upload_interval", 10000L, 10000L, y0.a, false);
        K = a("measurement.upload.debug_upload_interval", 1000L, 1000L, z0.a, false);
        L = a("measurement.upload.minimum_delay", 500L, 500L, A0.a, false);
        M = a("measurement.alarm_manager.minimum_interval", 60000L, 60000L, B0.a, false);
        N = a("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, C0.a, false);
        O = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, D0.a, false);
        P = a("measurement.upload.initial_upload_delay_time", 15000L, 15000L, F0.a, false);
        Q = a("measurement.upload.retry_time", 1800000L, 1800000L, H0.a, false);
        R = a("measurement.upload.retry_count", 6, 6, I0.a, false);
        S = a("measurement.upload.max_queue_time", 518400000L, 518400000L, J0.a, false);
        T = a("measurement.upload.google_signal_max_queue_time", 300000L, 300000L, K0.a, false);
        U = a("measurement.lifetimevalue.max_currency_tracked", 4, 4, L0.a, false);
        V = a("measurement.audience.filter_result_max_count", 200, 200, M0.a, false);
        W = a("measurement.upload.max_public_user_properties", 100, 100, null, false);
        X = a("measurement.upload.max_event_name_cardinality", 2000, 2000, null, false);
        Y = a("measurement.upload.max_public_event_params", 100, 100, null, false);
        Z = a("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, N0.a, false);
        a0 = a("measurement.service_client.reconnect_millis", 1000L, 1000L, O0.a, false);
        Boolean bool = Boolean.FALSE;
        b0 = a("measurement.test.boolean_flag", bool, bool, P0.a, false);
        c0 = a("measurement.test.string_flag", "---", "---", Q0.a, false);
        d0 = a("measurement.test.long_flag", -1L, -1L, S0.a, false);
        a("measurement.test.cached_long_flag", -1L, -1L, T0.a, true);
        e0 = a("measurement.test.int_flag", -2, -2, U0.a, false);
        Double valueOf = Double.valueOf(-3.0d);
        f0 = a("measurement.test.double_flag", valueOf, valueOf, V0.a, false);
        g0 = a("measurement.experiment.max_ids", 50, 50, W0.a, false);
        h0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, 27, X0.a, false);
        i0 = a("measurement.upload.max_event_parameter_value_length", 500, 500, Y0.a, true);
        j0 = a("measurement.max_bundles_per_iteration", 100, 100, Z0.a, false);
        k0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, a1.a, false);
        l0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, 7200000L, b1.a, false);
        m0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, 7, d1.a, false);
        n0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, 1, e1.a, false);
        o0 = a("measurement.rb.attribution.uri_scheme", "https", "https", g1.a, false);
        p0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", "google-analytics.com", h1.a, false);
        q0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", "privacy-sandbox/register-app-conversion", i1.a, false);
        r0 = a("measurement.session.engagement_interval", 3600000L, 3600000L, j1.a, false);
        s0 = a("measurement.rb.attribution.app_allowlist", "", "", k1.a, false);
        t0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", "_npa,npa|_fot,fot", l1.a, false);
        u0 = a("measurement.rb.attribution.event_params", "value|currency", "value|currency", m1.a, false);
        v0 = a("measurement.rb.attribution.query_parameters_to_remove", "", "", n1.a, false);
        w0 = a("measurement.rb.attribution.max_queue_time", 864000000L, 864000000L, p1.a, false);
        x0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, 16, q1.a, false);
        y0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, 90, r1.a, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, 0, s1.a, false);
        z0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, 1000, t1.a, false);
        Boolean bool2 = Boolean.TRUE;
        A0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, bool2, u1.a, false);
        B0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, bool2, v1.a, false);
        C0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, 3000, w1.a, false);
        D0 = a("measurement.quality.checksum", bool, bool, null, false);
        E0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, x1.a, false);
        F0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, y1.a, false);
        G0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, A1.a, true);
        H0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, B1.a, false);
        I0 = a("measurement.integration.disable_firebase_instance_id", bool, bool, C1.a, false);
        J0 = a("measurement.collection.service.update_with_analytics_fix", bool, bool, D1.a, false);
        K0 = a("measurement.service.storage_consent_support_version", 203600, 203600, E1.a, false);
        L0 = a("measurement.service.store_null_safelist", bool2, bool2, F1.a, false);
        M0 = a("measurement.service.store_safelist", bool2, bool2, H1.a, false);
        N0 = a("measurement.session_stitching_token_enabled", bool, bool, I1.a, false);
        O0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, bool, J1.a, true);
        P0 = a("measurement.gmscore_client_telemetry", bool, bool, a2.a, false);
        Q0 = a("measurement.rb.attribution.service", bool2, bool2, K1.a, true);
        R0 = a("measurement.rb.attribution.client2", bool2, bool2, M1.a, true);
        S0 = a("measurement.rb.attribution.uuid_generation", bool2, bool2, N1.a, false);
        T0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, bool2, O1.a, false);
        a("measurement.rb.attribution.followup1.service", bool, bool, P1.a, false);
        U0 = a("measurement.rb.attribution.retry_disposition", bool, bool, Q1.a, false);
        V0 = a("measurement.client.sessions.enable_fix_background_engagement", bool, bool, d2.a, false);
        W0 = a("measurement.set_default_event_parameters_propagate_clear.service.dev", bool2, bool2, R1.a, false);
        X0 = a("measurement.set_default_event_parameters_propagate_clear.client.dev", bool2, bool2, S1.a, false);
        Y0 = a("measurement.service.ad_impression.convert_value_to_double", bool2, bool2, T1.a, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, bool2, U1.a, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, bool, V1.a, false);
        Z0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, bool2, S.a, false);
        a1 = a("measurement.tcf.consent_fix", bool2, bool2, T.a, false);
        b1 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, bool2, U.a, false);
        c1 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, bool, L.a, false);
        d1 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, bool2, K.a, false);
        e1 = a("measurement.service.fix_stop_bundling_bug", bool2, bool2, O.a, false);
        f1 = a("measurement.fix_params_logcat_spam", bool2, bool2, N.a, false);
        g1 = a("measurement.gbraid_campaign.stop_lgclid", bool, bool, Z1.a, false);
        h1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", "gclid,gbraid,gad_campaignid", V.a, false);
        i1 = a("measurement.edpb.service", bool, bool, M.a, false);
        j1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", "_f,_v,_cmp", W.a, false);
        k1 = a("measurement.add_first_launch_logging_timestamp.service", bool, bool, c2.a, false);
        l1 = a("measurement.overlapping_bundles_fix", bool, bool, X.a, false);
    }

    public static e2 a(String str, Object obj, Object obj2, P p2, boolean z2) {
        e2 e2Var = new e2(str, obj, obj2, p2, null);
        if (z2) {
            a.add(e2Var);
        }
        return e2Var;
    }

    public static /* synthetic */ List b() {
        return a;
    }
}
